# Generated by Django 6.0.5 on 2026-05-27 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('sap', 'SAP fuel/procurement'), ('utility', 'Utility electricity'), ('travel', 'Corporate travel')], max_length=20)),
                ('ingestion_method', models.CharField(choices=[('csv_upload', 'CSV upload'), ('api', 'API'), ('manual', 'Manual')], default='csv_upload', max_length=30)),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('source_system', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_data_sources', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='data_sources', to='ingestion.tenant')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('valid', 'Valid'), ('invalid', 'Invalid'), ('normalized', 'Normalized'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('source_record_id', models.CharField(blank=True, max_length=255)),
                ('row_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='ingestion.datasource')),
            ],
            options={
                'ordering': ['data_source', 'row_number'],
            },
        ),
        migrations.CreateModel(
            name='NormalizedActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.PositiveSmallIntegerField(choices=[(1, 'Scope 1'), (2, 'Scope 2'), (3, 'Scope 3')])),
                ('activity_type', models.CharField(max_length=100)),
                ('activity_date', models.DateField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('unit', models.CharField(max_length=50)),
                ('normalized_quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('normalized_unit', models.CharField(max_length=50)),
                ('review_status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_info', 'Needs information')], default='pending', max_length=20)),
                ('suspicious', models.BooleanField(default=False)),
                ('flag_reason', models.TextField(blank=True)),
                ('normalized_payload', models.JSONField(blank=True, default=dict)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_activities', to=settings.AUTH_USER_MODEL)),
                ('raw_record', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='normalized_activity', to='ingestion.rawrecord')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='normalized_activities', to='ingestion.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('flagged', 'Flagged'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('commented', 'Commented')], max_length=30)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='ingestion.normalizedactivity')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['activity', 'timestamp'], name='ingestion_a_activit_48a91d_idx'), models.Index(fields=['actor', 'timestamp'], name='ingestion_a_actor_i_884eb9_idx'), models.Index(fields=['action'], name='ingestion_a_action_a594b7_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='rawrecord',
            index=models.Index(fields=['data_source', 'status'], name='ingestion_r_data_so_c9a922_idx'),
        ),
        migrations.AddConstraint(
            model_name='rawrecord',
            constraint=models.UniqueConstraint(fields=('data_source', 'row_number'), name='unique_raw_record_per_source_row'),
        ),
        migrations.AddIndex(
            model_name='normalizedactivity',
            index=models.Index(fields=['tenant', 'scope'], name='ingestion_n_tenant__163a1a_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedactivity',
            index=models.Index(fields=['tenant', 'review_status'], name='ingestion_n_tenant__7934f8_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedactivity',
            index=models.Index(fields=['suspicious'], name='ingestion_n_suspici_7aa199_idx'),
        ),
        migrations.AddIndex(
            model_name='datasource',
            index=models.Index(fields=['tenant', 'source_type'], name='ingestion_d_tenant__8e99b2_idx'),
        ),
        migrations.AddIndex(
            model_name='datasource',
            index=models.Index(fields=['uploaded_at'], name='ingestion_d_uploade_b22458_idx'),
        ),
    ]
